# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac2675a3f6b72905e77daea84777625652fbec7177177e485e5fb47954cba498f785ff10b281015c0a85d531aa42ca9c95b164de1726f84c9c568876d43e539e

test:
  secret_key_base: 3795d7c0642676e562393ad11a2e663c8bb59434c8968800e4ac1d84ebf546617232e4794260f497430498bd7b6a6d8e57ae161df9ded120ce738ae6c57404bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
